global:
  resolve_timeout: 5m


route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'fastapi_telegram'
  routes:
    - match:
        service: 'fastapi'
      receiver: 'fastapi_telegram'
    - match:
        service: 'rabbitmq'
      receiver: 'rabbitmq_telegram'


receivers:
- name: 'fastapi_telegram'
  telegram_configs:
  - bot_token: '8087085936:AAEiJ-GDBf3td2K6t6MHCH2qno4wWcDhdAc'
    chat_id: 1082202680
    parse_mode: 'Markdown'
    message: |
      {{ if eq .CommonLabels.severity "critical" }}
      *🔥 CRITICAL ALERT!*
      {{ else if eq .CommonLabels.severity "warning" }}
      *⚠️ WARNING!*
      {{ else }}
      *✅ INFO*
      {{ end }}
      *Alert:* {{ .CommonLabels.alertname }}
      *Status:* {{ .CommonLabels.severity }}
      *Description:* {{ .CommonAnnotations.description }}
      *Instance:* {{ .CommonLabels.instance }}


- name: 'rabbitmq_telegram'
  telegram_configs:
  - bot_token: '8087085936:AAEiJ-GDBf3td2K6t6MHCH2qno4wWcDhdAc'
    chat_id: 1082202680
    parse_mode: 'Markdown'
    message: |
      {{ if eq .CommonLabels.severity "critical" }}
      *🔥 CRITICAL ALERT!*
      {{ else if eq .CommonLabels.severity "warning" }}
      *⚠️ WARNING!*
      {{ else }}
      *✅ INFO*
      {{ end }}
      *Alert:* {{ .CommonLabels.alertname }}
      *Status:* {{ .CommonLabels.severity }}
      *Description:* {{ .CommonAnnotations.description }}
      *Instance:* {{ .CommonLabels.instance }}
